[build]
publish = "public"
command = 'hugo'

[taxonomies]
  tag = "tags"
  category = "categories"

[context.production.environment]
HUGO_VERSION = "0.146.6"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[build.environment]
  HUGO_VERSION = "0.146.5"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200